text = input("Введите строку: ")
result = (text.replace("a", "")
              .replace("e", "")
              .replace("i", "")
              .replace("o", "")
              .replace("u", ""))
print(result)