a = int(input("Введите число a: "))
b = int(input("Введите число b(b  не равное 0): "))
print("Сумма:", a + b)
print("Разность:", a - b)
print("Произведение:", a * b)
print("Частное:", a / b)
print("Остаток:", a % b)
print("Степень:", a ** b)
